//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelematicsData
    {
        public System.Guid Id { get; set; }
        public System.Guid VIN { get; set; }
        public Nullable<int> CurrentSpeed { get; set; }
        public Nullable<int> FuelLevel { get; set; }
        public Nullable<int> FuelUsed { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<int> RPM { get; set; }
        public Nullable<int> EngineSpeed { get; set; }
        public Nullable<int> EngineHours { get; set; }
        public Nullable<int> Mileage { get; set; }
        public Nullable<bool> IsDoorOpen { get; set; }
        public Nullable<System.TimeSpan> Idling { get; set; }
        public Nullable<bool> Ignition { get; set; }
        public Nullable<bool> SeatBelt { get; set; }
        public Nullable<bool> HarshAccelaration { get; set; }
        public Nullable<bool> HarshBraking { get; set; }
        public Nullable<bool> HarshCornering { get; set; }
        public Nullable<bool> TailGating { get; set; }
    }
}
