CREATE TABLE [dbo].[UserCompany]
(
	[Id] INT PRIMARY KEY NOT NULL,
	[User_Id] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [User](Id) NOT NULL,
	[Company_Id] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Company(Id) NOT NULL, 
)
